### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by dhararon** [hellpanderrr/pdf2xml#1]
Hi, i have this problems

1 .- global name 'gg' is not defined
2 .- global name 'pdfminer' is not defined
3 .- global name 'os' is not defined

Solutions:

1.- I dont know
2.- Add import pdfminer
3.- import os

Problem 1:
line 207, in group_by
    for p in concave(gg (find_tables(objs)[0] ,0 )[0],50,100)[0]:
NameError: global name 'gg' is not defined

Problem 2:
if j.hdistance(i) < 10 and j.vdistance(i) < 10 and j <> i and (type(j) == pdfminer.layout.LTRect  or type(j) == pdfminer.layout.LTLine) :
NameError: global name 'pdfminer' is not defined

Problem 3:
line 351, in makexml
    os.remove(f)
NameError: global name 'os' is not defined

**Comment by hellpanderrr** [comment]
Updated the description, but forgot to update the code..
Try now.
